version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Build CSV
          command: |
            . venv/bin/activate
            python main.py
      - store_artifacts:
          path: avurnavs.csv
          destination: avurnavs.csv
      - run:
          name: Setup Git
          command: |
            git config --global user.email "robot@circleci.com"
            git config --global user.name "Circle CI"
      - run:
          name: Push avurnavs to GitHub
          command: |
            git clone -q https://${GITHUB_TOKEN}@github.com/snosan-tools/avurnavs-fichiers.git /tmp/avurnavs-fichiers
            cp avurnavs.csv /tmp/avurnavs-fichiers/avurnavs.csv
            cd /tmp/avurnavs-fichiers
            if [ -n "$(git status --porcelain)" ]; then
              git commit -am "Update at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              git push -q origin master
            else
              echo "No changes";
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  cron:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
