version: 2
jobs:
  extract:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run: sudo apt install python-dev
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Build CSV
          command: python main.py
      - store_artifacts:
          path: avurnavs.csv
          destination: avurnavs.csv
